name: Monitor PostgreSQL Conferences

on:
  schedule:
    # Run daily at 9:00 AM UTC
    - cron: '0 9 * * *'

  # Allow manual triggering
  workflow_dispatch:

jobs:
  check-conferences:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      issues: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Check conferences
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
      run: |
        python scripts/check_conferences.py

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/conferences.json
        git diff --staged --quiet || git commit -m "Update conference data - $(date '+%Y-%m-%d %H:%M:%S')"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}